tp1: tp1_1.o tp1_2.o tp1_3.o
	gcc -o tp1 tp1_1.o tp1_2.o tp1_3.o

tp1_1.o: tp1_1.c
	gcc -Wall -Werror -W -c -o tp1_1.o tp1_1.c

tp1_2.o: tp1_2.c
	gcc -Wall -Werror -W -c -o tp1_2.o tp1_2.c

tp1_3.o: tp1_3.c
	gcc -Wall -Werror -W -c -o tp1_3.o tp1_3.c
