../bin/tp1: ../build/tp1_1.o ../build/tp1_2.o ../build/tp1_3.o
	gcc -o ../bin/tp1 ../build/tp1_1.o ../build/tp1_2.o ../build/tp1_3.o

../build/tp1_1.o: tp1_1.c
	gcc -Wall -Werror -W -c -o ../build/tp1_1.o tp1_1.c

../build/tp1_2.o: tp1_2.c
	gcc -Wall -Werror -W -c -o ../build/tp1_2.o tp1_2.c

../build/tp1_3.o: tp1_3.c
	gcc -Wall -Werror -W -c -o ../build/tp1_3.o tp1_3.c
