../bin/tp3: ../build/main.o ../build/tp3.o
	gcc -o ../bin/tp3 ../build/main.o ../build/tp3.o

../build/main.o: main.c
	gcc -Wall -Werror -W -c -o ../build/main.o main.c

../build/tp3.o: tp3.c
	gcc -Wall -Werror -W -c -o ../build/tp3.o tp3.c
