../bin/tp2: ../build/main.o ../build/tp2.o
	gcc -o ../bin/tp2 ../build/main.o ../build/tp2.o

../build/main.o: main.c
	gcc -Wall -Werror -W -c -o ../build/main.o main.c

../build/tp2.o: tp2.c
	gcc -Wall -Werror -W -c -o ../build/tp2.o tp2.c
